apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

# 📌 You Can Check the Binding With:
# kubectl get pv
# kubectl get pvc

# 🧠 Real-Life Analogy:
# Think of the PV as a parking spot and the PVC as someone reserving it. Once it’s 
# claimed, no one else can use that spot until the claim is released.

# ✅ What Happens When You Apply This:
# Kubernetes checks for a matching PersistentVolume.
# If a suitable PV is found (same or greater size, access mode), it gets bound to the PVC.
# The PVC can now be used in a Pod to mount the storage.

# 🔍 Explanation of Fields:
#        Field	                                Meaning
# metadata.name: local-pvc	             The name of the claim
# accessModes: ReadWriteOnce	           The Pod will mount the volume for read/write on a single node
# resources.requests.storage: 500Mi	     This Pod is asking for 500 MB of storage

# 📦 What Is a PersistentVolumeClaim (PVC)?
# A PVC is how an application requests persistent storage in Kubernetes. It asks 
# for specific storage resources and access modes, and Kubernetes matches it to 
# an available PersistentVolume (PV) (like the one from number 8).