apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
# ✅ Result:
# The container will have two environment variables:
# DB_USER=admin
# DB_PASS=password

# You can confirm by running:
# kubectl logs secret-pod

# 🔍 What This Does:
#    Field	                                           Meaning
# image: busybox	                             A tiny image used to test and troubleshoot
# command: ["sh", "-c", "env && sleep 3600"]	 Prints all env vars, then sleeps
# env[].valueFrom.secretKeyRef	               Injects secret values into the container as environment variables
# name: app-secret	                           Refers to the Secret created in number 6
# key: username/password	                     Specifies which keys in the Secret to us

# 📌 Why This Is Useful:
# Keeps secrets out of your Pod spec directly
# Works with apps expecting credentials via env vars
# Isolated per-Pod or per-container use