apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod-demo
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: local-pvc

# Check if the file exists:
# kubectl exec -it pvc-pod -- sh -c "cat /data/hello.txt"
