apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev
spec:
  serviceAccountName: nginx-sa
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

# kubectl create namespace dev
# kubectl create -f YAML-FILES/service-account-pod-definition.yaml