# 🔗Bind the Role to the dev Group
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-group-binding
  namespace: dev
subjects:
  - kind: Group
    name: dev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io

# kubectl apply -f USER-MANAGEMENT/rolebinding.yaml
